services:

  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  user-notes-backend:
    container_name: user-notes-backend
    build:
      context: ./user-notes-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_DRIVER_CLASSNAME=${DB_DRIVER_CLASSNAME}
      - SECURITY_USERNAME=${SECURITY_USERNAME}
      - SECURITY_PASSWORD=${SECURITY_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  postgres_data: